name: Commit Info
on: [push]

jobs:
  Change-Details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history so we can diff reliably

      - name: Print commit metadata and changed files (robust)
        env:
          ACTOR:        ${{ github.actor }}
          REPO:         ${{ github.repository }}
          BRANCH:       ${{ github.ref_name }}
          SHA:          ${{ github.sha }}
          MSG:          ${{ github.event.head_commit.message }}
          AUTHOR_NAME:  ${{ github.event.head_commit.author.name }}
          AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          TIMESTAMP:    ${{ github.event.head_commit.timestamp }}
          BEFORE:       ${{ github.event.before }}
        run: |
          set -euo pipefail

          echo "Repository : $REPO"
          echo "Branch     : $BRANCH"
          echo "Pushed by  : $ACTOR"
          echo "Author     : ${AUTHOR_NAME:-unknown} <${AUTHOR_EMAIL:-unknown}>"
          echo "Commit SHA : $SHA"
          echo "Timestamp  : ${TIMESTAMP:-N/A}"
          echo "Message:"
          echo "$MSG"
          echo "----------------------------------------"

          # Helper: does BEFORE exist as a commit object?
          has_before() {
            [ -n "${BEFORE:-}" ] \
              && [ "$BEFORE" != "0000000000000000000000000000000000000000" ] \
              && git cat-file -e "${BEFORE}^{commit}" 2>/dev/null
          }

          if has_before; then
            echo "Changed files since BEFORE=$BEFORE:"
            # Try a normal diff; if it fails for any reason, fall back to showing this commit only
            git diff --name-status "$BEFORE" "$SHA" || git show --name-status --oneline "$SHA"
          else
            # BEFORE missing (new branch, mirror, or force-push). Use the parent of this commit if it exists.
            PARENT="$(git rev-list --max-parents=1 --parents -n 1 "$SHA" | awk '{print $2}')"
            if [ -n "$PARENT" ]; then
              echo "BEFORE not available; using parent commit $PARENT"
              git diff --name-status "$PARENT" "$SHA"
            else
              echo "Root commit; listing files in this commit:"
              git show --name-status --oneline "$SHA"
            fi
          fi
