name: Mirror to GitHub
on: [push]

jobs:
  Change-Details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print commit metadata and changed files
        env:
          ACTOR:       ${{ github.actor }}
          REPO:        ${{ github.repository }}
          BRANCH:      ${{ github.ref_name }}
          SHA:         ${{ github.sha }}
          MSG:         ${{ github.event.head_commit.message }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          TIMESTAMP:   ${{ github.event.head_commit.timestamp }}
          BEFORE:      ${{ github.event.before }}
        run: |
          set -e
          echo "Repository : $REPO"
          echo "Branch     : $BRANCH"
          echo "Pushed by  : $ACTOR"
          echo "Author     : ${AUTHOR_NAME:-unknown} <${AUTHOR_EMAIL:-unknown}>"
          echo "Commit SHA : $SHA"
          echo "Timestamp  : ${TIMESTAMP:-N/A}"
          echo "Message:"
          echo "$MSG"
          echo "----------------------------------------"

          # List changed files
          if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            echo "No 'before' SHA (new branch or first push). Files in this commit:"
            git show --name-status --oneline "$SHA"
          else
            echo "Changed files since BEFORE=$BEFORE:"
            git diff --name-status "$BEFORE" "$SHA"
          fi
