name: Mirror to GitHub
on: [push]

jobs:
  mirror:
    if: ${{ github.actor != 'mirror-bot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to GitHub (skip if same commit)
        env:
          GH_USER: ${{ secrets.GHUB_USERNAME }}
          GH_TOKEN: ${{ secrets.GHUB_TOKEN }}
          GH_HOST: github.com
          GH_REPO: CI-CD-on-K8s-Group2
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          git config user.name  "Gitea Mirror Bot"
          git config user.email "mirror@${GH_HOST}"

          GH_URL="https://${GH_USER}:${GH_TOKEN}@${GH_HOST}/${GH_USER}/${GH_REPO}.git"

          # Find the HEAD commit on GitHub for this branch (may be empty on first push)
          REMOTE_SHA=$(git ls-remote "$GH_URL" "refs/heads/${BRANCH}" | awk '{print $1}')
          LOCAL_SHA=$(git rev-parse HEAD)

          if [ "$REMOTE_SHA" = "$LOCAL_SHA" ]; then
            echo "GitHub already has this commit on ${BRANCH}; skipping push."
            exit 0
          fi

          # Add/refresh remote and push
          git remote remove github 2>/dev/null || true
          git remote add github "$GH_URL"
          git push github HEAD:${BRANCH}
